import { StyleSheet } from 'react-native';
import { COLORS, SPACING, SIZES } from '../constants/theme';

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.m, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  backBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border },
  headerTitle: { fontSize: 15, fontWeight: '800', color: COLORS.text, flex: 1, textAlign: 'center' },
  addBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary },
  roleNote: { fontSize: 12, color: COLORS.textSecondary, backgroundColor: COLORS.surface, padding: 12, borderRadius: 12, marginBottom: 14, lineHeight: 17 },
  empty: { color: COLORS.textSecondary, fontSize: 14, paddingVertical: 20, textAlign: 'center' },
  card: { backgroundColor: COLORS.surface, borderRadius: SIZES.radiusLg, borderWidth: 1, borderColor: COLORS.border, padding: SPACING.m, marginBottom: 12 },
  cardHead: { flexDirection: 'row', alignItems: 'flex-start' },
  cardTitle: { fontSize: 15, fontWeight: '800', color: COLORS.text },
  cardMeta: { fontSize: 11, color: COLORS.textSecondary, marginTop: 2 },
  editBtn: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primarySoft },
  diag: { fontSize: 13, fontWeight: '700', color: COLORS.text, marginTop: 8 },
  imageLink: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10 },
  imageLinkText: { color: COLORS.primary, fontWeight: '700', fontSize: 12 },
  attachBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: COLORS.primary, borderStyle: 'dashed' },
  attachText: { color: COLORS.primary, fontWeight: '700', fontSize: 13 },
  notesText: { fontSize: 13, color: COLORS.textSecondary, marginTop: 6, lineHeight: 19 },
  vitalsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  vitalChip: { backgroundColor: COLORS.primarySoft, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  vitalChipText: { fontSize: 11, color: COLORS.primary, fontWeight: '700' },
  noteItem: { flexDirection: 'row', gap: 8, marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: COLORS.border, alignItems: 'flex-start' },
  noteText: { fontSize: 12, color: COLORS.text, lineHeight: 17 },
  noteMeta: { fontSize: 10, color: COLORS.textSecondary, marginTop: 2 },
  addNoteBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 12, alignSelf: 'flex-start' },
  addNoteText: { color: COLORS.primary, fontWeight: '700', fontSize: 12 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: COLORS.background, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: SPACING.m, maxHeight: '90%' },
  sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text },
  label: { fontSize: 12, fontWeight: '700', color: COLORS.textSecondary, marginTop: 12, marginBottom: 6 },
  input: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, color: COLORS.text },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  typeChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.white },
  typeChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  typeChipText: { fontSize: 12, fontWeight: '700', color: COLORS.textSecondary },
  typeChipTextActive: { color: COLORS.white },
  vitalsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  vitalInputWrap: { width: '47%' },
  vitalLabel: { fontSize: 11, color: COLORS.textSecondary, marginBottom: 4 },
  vitalInput: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, fontSize: 13, color: COLORS.text },
  saveBtn: { backgroundColor: COLORS.primary, borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 18 },
  saveText: { color: COLORS.white, fontWeight: '800', fontSize: 15 },
  noteSheet: { backgroundColor: COLORS.background, borderRadius: 18, padding: SPACING.l },
  cancelBtn: { paddingVertical: 15, paddingHorizontal: 18, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center' },
  cancelText: { color: COLORS.textSecondary, fontWeight: '700' },
});

export default styles;
