import { Platform, StyleSheet } from 'react-native';
import { COLORS, SPACING } from '../constants/theme';

export default StyleSheet.create({
  // Maroon, not white: this colour fills the status-bar inset above the curved
  // header. Everything below is covered by `container`.
  safeArea: { flex: 1, backgroundColor: COLORS.primary },
  container: { flex: 1, backgroundColor: COLORS.surface },

  referralBanner: {
    flexDirection: 'row', alignItems: 'center',
    marginHorizontal: SPACING.m, marginTop: SPACING.s,
    padding: 12, borderRadius: 14,
    backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#bfdbfe',
  },
  referralBannerIcon: {
    width: 34, height: 34, borderRadius: 17, backgroundColor: COLORS.white,
    alignItems: 'center', justifyContent: 'center', marginRight: 10,
  },
  referralBannerTitle: { fontSize: 13, fontWeight: '800', color: '#1e40af' },
  referralBannerBody: { fontSize: 12, color: '#1e40af', marginTop: 2, lineHeight: 16 },

  primaryHeader: {
    backgroundColor: COLORS.primary,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 24 : 40,
    paddingBottom: 44,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.l,
  },
  userInfoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarMiniWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  welcomeTextCol: {
    justifyContent: 'center',
  },
  headerGoodMorning: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '500',
  },
  headerUserName: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 1,
  },
  headerRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 6,
  },
  locationText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '600',
  },
  notificationBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 10,
    right: 11,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FF8A00',
  },
  headerContent: {
    marginTop: SPACING.s,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.white,
    lineHeight: 30,
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 6,
    lineHeight: 20,
  },
  headerAppointmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 22,
  },
  // Order strip shares the appointment card's look; the second and later cards
  // sit closer together, and one needing the patient's approval is brighter.
  headerOrderCard: { marginTop: 10 },
  headerOrderCardAction: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderColor: 'rgba(255,255,255,0.4)',
  },
  headerMoreOrders: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    marginTop: 2,
  },
  headerMoreOrdersText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    fontWeight: '700',
  },
  headerApptLeft: {
    flex: 1,
  },
  headerApptLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '500',
  },
  headerApptValue: {
    fontSize: 13,
    color: COLORS.white,
    fontWeight: '600',
    marginTop: 3,
  },
  // Low-key affordance so the patient knows the card is actionable.
  headerApptHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
  },
  headerApptHint: {
    fontSize: 10.5,
    color: 'rgba(255,255,255,0.65)',
    fontWeight: '600',
    letterSpacing: 0.2,
  },

  quickActionsSection: {
    paddingHorizontal: 20,
    marginTop: -26,
    marginBottom: SPACING.m,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  quickActionCard: {
    alignItems: 'center',
    width: '18%',
  },
  quickActionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.text,
    textAlign: 'center',
  },
  // Emergency quick-action label — red so the tile stands out.
  emergencyQuickLabel: {
    color: '#B02A37',
    fontWeight: '700',
  },

  premiumSection: {
    paddingHorizontal: 20,
    marginBottom: SPACING.m,
  },
  premiumCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    padding: 16,
    elevation: 3,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  premiumIconContainer: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  premiumTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  premiumSubtitle: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 2,
  },

  vitalsScrollContent: {
    paddingLeft: 20,
    paddingRight: 8,
  },
  vitalCard: {
    width: 130,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 20,
    padding: 14,
    marginRight: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
  },
  vitalIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  vitalLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  vitalValue: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.text,
    marginTop: 3,
  },
  vitalUnit: {
    fontSize: 11,
    fontWeight: '400',
    color: COLORS.textSecondary,
  },

  searchSectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: SPACING.m,
    paddingHorizontal: 20,
  },
  searchBarPlaceholder: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.m,
    marginHorizontal: 20,
    borderRadius: 16,
    height: 52,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  searchPlaceholderText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },

  section: {
    marginTop: SPACING.m,
    marginBottom: SPACING.m,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.m,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.text,
  },
  seeAllText: {
    fontSize: 13,
    color: COLORS.primary,
    fontWeight: '600',
  },

  verticalList: {
    paddingHorizontal: 20,
  },
  fullWidthDoctorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  doctorImgPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#E6FFFA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  doctorInitials: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.primary,
  },
  docInfoCol: {
    flex: 1,
  },
  docName: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.text,
  },
  docSpec: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
    fontWeight: '500',
  },
  docRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  ratingText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  bookBtnSmall: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookBtnBooked: {
    backgroundColor: '#d1fae5',
  },
  bookBtnTextSmall: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  bookBtnTextBooked: {
    color: '#065f46',
  },

  emergencyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FEB2B2',
    borderRadius: 20,
    padding: 16,
    marginHorizontal: 20,
    elevation: 2,
    shadowColor: '#dc3545',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  emergencyIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#dc3545',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  emergencyTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.text,
  },
  emergencySubtitle: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  emergencyCallBtn: {
    backgroundColor: '#dc3545',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
  },
  emergencyCallBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: SPACING.l,
    minHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.l,
    paddingBottom: SPACING.m,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
  },
  currentLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.secondary,
    padding: SPACING.m,
    borderRadius: 16,
    marginBottom: SPACING.l,
  },
  currentLocIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  currentLocTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.primary,
  },
  currentLocSub: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  modalSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginBottom: SPACING.m,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  locationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.m,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border + '50',
  },
  activeLocationItem: {
    backgroundColor: COLORS.secondary + '20',
  },
  locationItemText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.text,
    marginLeft: 12,
    fontWeight: '500',
  },
  activeLocationItemText: {
    color: COLORS.primary,
    fontWeight: '700',
  },
});