import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

export const translations = {
  English: {
    welcome: 'Welcome to Healio',
    select_language: 'Select Language',
    next: 'Next',
    get_started: 'Get Started',
    phone_number: 'Phone Number',
    send_otp: 'Send OTP',
    verify_otp: 'Verify OTP',
    home: 'Home',
    appointments: 'Appointments',
    services: 'Services',
    records: 'Records',
    profile: 'Profile',
    nav_home: 'Home',
    nav_appointments: 'Appts',
    nav_services: 'Services',
    nav_records: 'Records',
    nav_orders: 'Orders',
    nav_profile: 'Profile',
    emergency: 'Emergency',
    search_hint: 'Search doctors, hospitals...',
    upcoming: 'Upcoming Appointment',
    recent_prescription: 'Recent Prescription',
    quick_actions: 'Quick Actions',
    // Specialties
    cardiologist: 'Cardiologist',
    dermatologist: 'Dermatologist',
    orthopedic: 'Orthopedic',
    pediatrician: 'Pediatrician',
    // Services
    doctors: 'Doctors',
    labs: 'Labs',
    pharmacy: 'Medicine',
    medicine: 'Medicine',
    hospitals: 'Hospitals',
    home_care: 'Home Care',
    emergency_service: 'Emergency',
    ambulance: 'Ambulance',
    insurance: 'Insurance',
    // Descriptions
    doctors_desc: 'Book consultations with specialists nearby',
    labs_desc: 'Diagnostic tests & health packages at home',
    pharmacy_desc: 'Order medicines & healthcare products',
    medicine_desc: 'Order medicines & healthcare products',
    hospitals_desc: 'Find nearby hospitals & clinics',
    home_care_desc: 'Nursing & assisted living',
    emergency_desc: 'Immediate medical help',
    ambulance_desc: '24/7 emergency transport',
    insurance_desc: 'Health insurance & claims',
    // Home Screen UI
    main_services: 'Main Services',
    top_doctors: 'Top Doctors Near You',
    find_healthcare: 'Find your healthcare needs',
    see_all: 'See All',
    view_all: 'View All',
    join_now: 'Join Now',
    book_now: 'Book',
    emergency_banner_title: 'Emergency Services',
    emergency_banner_sub: 'Call ambulance or find ER nearby',
    select_city: 'Select City',
    use_current_location: 'Use Current Location',
    gps_precise: 'Using GPS for precise location',
    popular_cities: 'Popular Cities',
    // Services Screen UI
    search_services: 'Search healthcare services...',
    search_in: 'Search in',
    all: 'All',
    top_rated: 'Top Rated',
    nearest: 'Nearest',
    explore_categories: 'Explore Categories',
    categories_sub: 'Find the right care for you',
    // Records/Reports Hub UI
    my_records: 'My Medical Records',
    lab_reports: 'Lab Reports',
    prescriptions: 'Prescriptions',
    payments: 'Payments',
    medical_history: 'Medical History',
    view_report: 'View Report',
    health_insights: 'Health Insights',
    summary: 'Summary',
    // Insights UI
    ai_summary: 'AI Health Summary',
    vitals: 'Vitals',
    heart_rate: 'Heart Rate',
    blood_pressure: 'Blood Pressure',
    blood_sugar: 'Blood Sugar',
    activity: 'Daily Activity',
    steps: 'Steps',
    calories: 'Calories',
    sleep: 'Sleep',
    wellness_score: 'Wellness Score',
    recommendations: 'Recommendations',
    // Added keys for absolute application-wide translation
    good_morning: 'Good Morning',
    good_afternoon: 'Good Afternoon',
    good_evening: 'Good Evening',
    there: 'there',
    clear_filter: 'Clear Filter',
    timeline: 'Timeline',
    medical_records: 'Medical Records',
    centralized_vault: 'Centralized medical vault for your family',
    export_report: 'Export Report',
    items: 'items',
    no_records: 'No records found for this category',
    my_appointments: 'My Appointments',
    upcoming_tab: 'Upcoming',
    past_tab: 'Past',
    cancelled_tab: 'Cancelled',
    reschedule: 'Reschedule',
    cancel: 'Cancel',
    no_appointments: 'No appointments',
    all_services: 'All Services',
    find_nearby: 'Find nearby',
    search_in_cat: 'Search in',
    no_results: 'No results found',
    my_profile: 'My Profile',
    account_settings: 'Account Settings',
    personal_info: 'Personal Information',
    family_profiles: 'Family Profiles',
    manage_addresses: 'Manage Addresses',
    notification_settings: 'Notification Settings',
    health_records: 'Health & Records',
    medical_reports: 'Medical Reports',
    lab_test_history: 'Lab Test History',
    health_analytics: 'Health Analytics',
    download_data_center: 'Download Data Center',
    payments_support: 'Payments & Support',
    payments_billing: 'Payments & Billing',
    insurance_details: 'Insurance Details',
    help_support: 'Help & Support',
    about_healio: 'About Healio',
    weight: 'Weight',
    height: 'Height',
    blood: 'Blood',
    login: 'Login',
    signup: 'Sign Up',
    create_account: 'Create Account',
    whos_using: "Who's using Healio?",
    add_profile: 'Add Profile',
    setup_profile: 'Set Up Your Profile',
    skip_for_now: 'Skip for now',
    date_of_birth: 'Date of Birth',
    gender: 'Gender',
    optional: 'Optional',
    emergency_contact: 'Emergency Contact',
    already_have_account: 'Already have an account?',
    dont_have_account: "Don't have an account?",
    male: 'Male',
    female: 'Female',
    other_gender: 'Other',
    tagline: 'Your health companion',
    // Patient registration
    signup_subtitle: 'Join Healio to manage your health journey',
    full_name: 'Full Name',
    full_name_ph: 'Enter your full name',
    phone_ph: '10-digit mobile number',
    dob_ph: 'Select date of birth',
    email_address: 'Email Address',
    email_ph: 'Enter email address (optional)',
    blood_group: 'Blood Group',
    blood_group_ph: 'Select blood group (optional)',
    select_blood_group: 'Select Blood Group',
    clear_selection: 'Clear selection',
  },
  Bengali: {
    welcome: 'Healio-তে স্বাগতম',
    select_language: 'ভাষা নির্বাচন করুন',
    next: 'পরবর্তী',
    get_started: 'শুরু করুন',
    phone_number: 'ফোন নম্বর',
    send_otp: 'OTP পাঠান',
    verify_otp: 'OTP যাচাই করুন',
    home: 'হোম',
    appointments: 'অ্যাপয়েন্টমেন্ট',
    services: 'পরিষেবা',
    records: 'রেকর্ড',
    profile: 'প্রোফাইল',
    nav_home: 'হোম',
    nav_appointments: 'অ্যাপয়েন্ট.',
    nav_services: 'সেবা',
    nav_records: 'রেকর্ড',
    nav_orders: 'অর্ডার',
    nav_profile: 'প্রোফাইল',
    emergency: 'জরুরী অবস্থা',
    search_hint: 'ডাক্তার, হাসপাতাল খুঁজুন...',
    upcoming: 'আসন্ন অ্যাপয়েন্টমেন্ট',
    recent_prescription: 'সাম্প্রতিক প্রেসক্রিপশন',
    quick_actions: 'দ্রুত পদক্ষেপ',
    // Specialties
    cardiologist: 'হৃদরোগ বিশেষজ্ঞ',
    dermatologist: 'চর্মরোগ বিশেষজ্ঞ',
    orthopedic: 'অস্থিরোগ বিশেষজ্ঞ',
    pediatrician: 'শিশু বিশেষজ্ঞ',
    // Services
    doctors: 'ডাক্তাররা',
    labs: 'ল্যাবস',
    pharmacy: 'ওষুধ',
    medicine: 'ওষুধ',
    hospitals: 'হাসপাতাল',
    home_care: 'হোম কেয়ার',
    emergency_service: 'জরুরী',
    ambulance: 'অ্যাম্বুলেন্স',
    insurance: 'বীমা',
    // Descriptions
    doctors_desc: 'কাছাকাছি বিশেষজ্ঞদের সাথে পরামর্শ বুক করুন',
    labs_desc: 'বাড়িতে ডায়াগনস্টিক পরীক্ষা এবং স্বাস্থ্য প্যাকেজ',
    pharmacy_desc: 'ওষুধ এবং স্বাস্থ্যসেবা পণ্য অর্ডার করুন',
    medicine_desc: 'ওষুধ এবং স্বাস্থ্যসেবা পণ্য অর্ডার করুন',
    hospitals_desc: 'আশেপাশের হাসপাতাল এবং ক্লিনিক খুঁজুন',
    home_care_desc: 'নার্সিং এবং সহায়ক জীবনযাপন',
    emergency_desc: 'অবিলম্বে চিকিৎসা সহায়তা',
    ambulance_desc: '২৪/৭ জরুরি পরিবহন',
    insurance_desc: 'স্বাস্থ্য বীমা এবং দাবি',
    // Home Screen UI
    main_services: 'প্রধান পরিষেবাগুলি',
    top_doctors: 'আপনার কাছের শীর্ষ ডাক্তার',
    find_healthcare: 'আপনার স্বাস্থ্যসেবা প্রয়োজন খুঁজুন',
    see_all: 'সব দেখুন',
    view_all: 'সব দেখুন',
    join_now: 'এখনই যোগ দিন',
    book_now: 'বুক করুন',
    emergency_banner_title: 'জরুরী পরিষেবা',
    emergency_banner_sub: 'অ্যাম্বুলেন্স কল করুন বা কাছাকাছি ইআর খুঁজুন',
    select_city: 'শহর নির্বাচন করুন',
    use_current_location: 'বর্তমান অবস্থান ব্যবহার করুন',
    gps_precise: 'সুনির্দিষ্ট অবস্থানের জন্য জিপিএস ব্যবহার করা হচ্ছে',
    popular_cities: 'জনপ্রিয় শহর',
    // Services Screen UI
    search_services: 'স্বাস্থ্যসেবা অনুসন্ধান করুন...',
    search_in: 'অনুসন্ধান করুন',
    all: 'সব',
    top_rated: 'সেরা রেটেড',
    nearest: 'নিকটতম',
    explore_categories: 'বিভাগ দেখুন',
    categories_sub: 'আপনার জন্য সঠিক যত্ন খুঁজুন',
    // Records/Reports Hub UI
    my_records: 'আমার চিকিৎসা রেকর্ড',
    lab_reports: 'ল্যাব রিপোর্ট',
    prescriptions: 'প্রেসক্রিপশন',
    payments: 'পেমেন্ট',
    medical_history: 'চিকিৎসা ইতিহাস',
    view_report: 'রিপোর্ট দেখুন',
    health_insights: 'স্বাস্থ্য অন্তর্দৃষ্টি',
    summary: 'সারসংক্ষেপ',
    // Insights UI
    ai_summary: 'এআই স্বাস্থ্য সারসংক্ষেপ',
    vitals: 'ভাইটালস',
    heart_rate: 'হার্ট রেট',
    blood_pressure: 'রক্তচাপ',
    blood_sugar: 'ব্লাড সুগার',
    activity: 'দৈনিক কার্যকলাপ',
    steps: 'পদক্ষেপ',
    calories: 'ক্যালোরি',
    sleep: 'ঘুম',
    wellness_score: 'ওয়েলনেস স্কোর',
    recommendations: 'সুপারিশ',
    // Added keys for absolute application-wide translation
    good_morning: 'শুভ সকাল',
    good_afternoon: 'শুভ অপরাহ্ন',
    good_evening: 'শুভ সন্ধ্যা',
    there: 'সেখানে',
    clear_filter: 'ফিল্টার মুছুন',
    timeline: 'সময়রেখা',
    medical_records: 'চিকিৎসা রেকর্ড',
    centralized_vault: 'আপনার পরিবারের জন্য কেন্দ্রীভূত চিকিৎসা ভল্ট',
    export_report: 'রিপোর্ট রপ্তানি',
    items: 'টি আইটেম',
    no_records: 'এই বিভাগের জন্য কোনো রেকর্ড পাওয়া যায়নি',
    my_appointments: 'আমার অ্যাপয়েন্টমেন্ট',
    upcoming_tab: 'আসন্ন',
    past_tab: 'অতীত',
    cancelled_tab: 'বাতিল',
    reschedule: 'পুনঃনির্ধারণ',
    cancel: 'বাতিল করুন',
    no_appointments: 'কোনো অ্যাপয়েন্টমেন্ট নেই',
    all_services: 'সব পরিষেবা',
    find_nearby: 'কাছাকাছি খুঁজুন',
    search_in_cat: 'অনুসন্ধান করুন',
    no_results: 'কোনো ফলাফল পাওয়া যায়নি',
    my_profile: 'আমার প্রোফাইল',
    account_settings: 'অ্যাকাউন্ট সেটিংস',
    personal_info: 'ব্যক্তিগত তথ্য',
    family_profiles: 'পারিবারিক প্রোফাইল',
    manage_addresses: 'ঠিকানা পরিচালনা করুন',
    notification_settings: 'বিজ্ঞপ্তি সেটিংস',
    health_records: 'স্বাস্থ্য এবং রেকর্ড',
    medical_reports: 'চিকিৎসা রিপোর্ট',
    lab_test_history: 'ল্যাব পরীক্ষার ইতিহাস',
    health_analytics: 'স্বাস্থ্য বিশ্লেষণ',
    download_data_center: 'ডাটা সেন্টার ডাউনলোড করুন',
    payments_support: 'পেমেন্ট এবং সহায়তা',
    payments_billing: 'পেমেন্ট এবং বিলিং',
    insurance_details: 'বীমা বিবরণ',
    help_support: 'সাহায্য এবং সমর্থন',
    logout: 'লগআউট',
    weight: 'ওজন',
    height: 'উচ্চতা',
    blood: 'রক্ত',
    login: 'লগইন',
    signup: 'নিবন্ধন করুন',
    create_account: 'অ্যাকাউন্ট তৈরি করুন',
    whos_using: 'কে Healio ব্যবহার করছেন?',
    add_profile: 'প্রোফাইল যোগ করুন',
    setup_profile: 'প্রোফাইল সেট আপ করুন',
    skip_for_now: 'আপাতত বাদ দিন',
    date_of_birth: 'জন্ম তারিখ',
    gender: 'লিঙ্গ',
    optional: 'ঐচ্ছিক',
    emergency_contact: 'জরুরী যোগাযোগ',
    already_have_account: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    dont_have_account: 'অ্যাকাউন্ট নেই?',
    male: 'পুরুষ',
    female: 'মহিলা',
    other_gender: 'অন্যান্য',
    tagline: 'আপনার স্বাস্থ্য সঙ্গী',
    // Patient registration
    signup_subtitle: 'আপনার স্বাস্থ্য যাত্রা পরিচালনা করতে Healio-তে যোগ দিন',
    full_name: 'পুরো নাম',
    full_name_ph: 'আপনার পুরো নাম লিখুন',
    phone_ph: '১০-সংখ্যার মোবাইল নম্বর',
    dob_ph: 'জন্ম তারিখ নির্বাচন করুন',
    email_address: 'ইমেল ঠিকানা',
    email_ph: 'ইমেল ঠিকানা লিখুন (ঐচ্ছিক)',
    blood_group: 'রক্তের গ্রুপ',
    blood_group_ph: 'রক্তের গ্রুপ নির্বাচন করুন (ঐচ্ছিক)',
    select_blood_group: 'রক্তের গ্রুপ নির্বাচন করুন',
    clear_selection: 'নির্বাচন সাফ করুন',
  },
  Hindi: {
    welcome: 'Healio में आपका स्वागत है',
    select_language: 'भाषा चुनें',
    next: 'अगला',
    get_started: 'शुरू करें',
    phone_number: 'फ़ोन नंबर',
    send_otp: 'ओटीपी भेजें',
    verify_otp: 'ओटीपी सत्यापित करें',
    home: 'होम',
    appointments: 'अपॉइंटमेंट',
    services: 'सेवाएं',
    records: 'रिकॉर्ड',
    profile: 'प्रोफ़ाइल',
    nav_home: 'होम',
    nav_appointments: 'अपॉइंट.',
    nav_services: 'सेवाएं',
    nav_records: 'रिकॉर्ड',
    nav_orders: 'ऑर्डर',
    nav_profile: 'प्रोफ़ाइल',
    emergency: 'आपातकालीन',
    search_hint: 'डॉक्टर, अस्पताल खोजें...',
    upcoming: 'आगामी अपॉइंटमेंट',
    recent_prescription: 'हालिया नुस्खा',
    quick_actions: 'त्वरित कार्रवाई',
    // Specialties
    cardiologist: 'हृदय रोग विशेषज्ञ',
    dermatologist: 'त्वचा विशेषज्ञ',
    orthopedic: 'हड्डी रोग विशेषज्ञ',
    pediatrician: 'बाल रोग विशेषज्ञ',
    // Services
    doctors: 'डॉक्टर',
    labs: 'लैब',
    pharmacy: 'दवा',
    medicine: 'दवा',
    hospitals: 'अस्पताल',
    home_care: 'होम केयर',
    emergency_service: 'आपातकालीन',
    ambulance: 'एम्बुलेंस',
    insurance: 'बीमा',
    // Descriptions
    doctors_desc: 'पास के विशेषज्ञों के साथ परामर्श बुक करें',
    labs_desc: 'घर पर नैदानिक परीक्षण और स्वास्थ्य पैकेज',
    pharmacy_desc: 'दवाएं और स्वास्थ्य देखभाल उत्पाद ऑर्डर करें',
    medicine_desc: 'दवाएं और स्वास्थ्य देखभाल उत्पाद ऑर्डर करें',
    hospitals_desc: 'पास के अस्पताल और क्लीनिक खोजें',
    home_care_desc: 'नर्सिंग और सहायता प्राप्त जीवन',
    emergency_desc: 'तत्काल चिकित्सा सहायता',
    ambulance_desc: '24/7 आपातकालीन परिवहन',
    insurance_desc: 'स्वास्थ्य बीमा और दावे',
    // Home Screen UI
    main_services: 'मुख्य सेवाएं',
    top_doctors: 'आपके पास के शीर्ष डॉक्टर',
    find_healthcare: 'अपनी स्वास्थ्य देखभाल ज़रूरतें खोजें',
    see_all: 'सभी देखें',
    view_all: 'सभी देखें',
    join_now: 'अभी जुड़ें',
    book_now: 'बुक करें',
    emergency_banner_title: 'आपातकालीन सेवाएँ',
    emergency_banner_sub: 'एम्बुलेंस बुलाएं या पास के ईआर खोजें',
    select_city: 'शहर चुनें',
    use_current_location: 'वर्तमान स्थान का उपयोग करें',
    gps_precise: 'सटीक स्थान के लिए जीपीएस का उपयोग करना',
    popular_cities: 'लोकप्रिय शहर',
    // Services Screen UI
    search_services: 'स्वास्थ्य सेवाओं की खोज करें...',
    search_in: 'इसमें खोजें',
    all: 'सभी',
    top_rated: 'टॉप रेटेड',
    nearest: 'निकटतम',
    explore_categories: 'श्रेणियां देखें',
    categories_sub: 'अपने लिए सही देखभाल खोजें',
    // Records/Reports Hub UI
    my_records: 'मेरे मेडिकल रिकॉर्ड',
    lab_reports: 'लैब रिपोर्ट',
    prescriptions: 'पर्चे',
    payments: 'भुगतान',
    medical_history: 'चिकित्सा इतिहास',
    view_report: 'रिपोर्ट देखें',
    health_insights: 'स्वास्थ्य अंतर्दৃষ্টি',
    summary: 'सारांश',
    // Insights UI
    ai_summary: 'एआई स्वास्थ्य सारांश',
    vitals: 'वाइटल्स',
    heart_rate: 'हृदय गति',
    blood_pressure: 'रक्तचाप',
    blood_sugar: 'ब्लड शुगर',
    activity: 'दैनिक गतिविधि',
    steps: 'कदम',
    calories: 'कैलोरी',
    sleep: 'नींद',
    wellness_score: 'वेलनेस स्कोर',
    recommendations: 'सिफारिशें',
    // Added keys for absolute application-wide translation
    good_morning: 'शुभ प्रभात',
    good_afternoon: 'नमस्कार',
    good_evening: 'शुभ संध्या',
    there: 'वहाँ',
    clear_filter: 'फ़िल्टर हटाएँ',
    timeline: 'समयरेखा',
    medical_records: 'मेडिकल रिकॉर्ड',
    centralized_vault: 'आपके परिवार के लिए केंद्रीकृत मेडिकल वॉल्ट',
    export_report: 'रिपोर्ट निर्यात',
    items: 'आइटम',
    no_records: 'इस श्रेणी के लिए कोई रिकॉर्ड नहीं मिला',
    my_appointments: 'मेरे अपॉइंटमेंट',
    upcoming_tab: 'आगामी',
    past_tab: 'विगत',
    cancelled_tab: 'रद्द',
    reschedule: 'पुनर्निर्धारित करें',
    cancel: 'रद्द करें',
    no_appointments: 'कोई अपॉइंटमेंट नहीं',
    all_services: 'सभी सेवाएं',
    find_nearby: 'पास में खोजें',
    search_in_cat: 'खोजें',
    no_results: 'कोई परिणाम नहीं मिला',
    my_profile: 'मेरी प्रोफाइल',
    account_settings: 'अकाउंट सेटिंग्स',
    personal_info: 'व्यक्तिगत जानकारी',
    family_profiles: 'पारिवारिक प्रोफाइल',
    manage_addresses: 'पते प्रबंधित करें',
    notification_settings: 'अधिसूचना सेटिंग्स',
    health_records: 'स्वास्थ्य और रिकॉर्ड',
    medical_reports: 'मेडिकल रिपोर्ट',
    lab_test_history: 'लैब टेस्ट इतिहास',
    health_analytics: 'स्वास्थ्य विश्लेषिकी',
    download_data_center: 'डेटा सेंटर डाउनलोड करें',
    payments_support: 'भुगतान और सहायता',
    payments_billing: 'भुगतान और बिलिंग',
    insurance_details: 'बीमा विवरण',
    help_support: 'सहायता और समर्थन',
    logout: 'लॉगआउट',
    weight: 'वजन',
    height: 'लंबाई',
    blood: 'रक्त',
    login: 'लॉगिन',
    signup: 'साइन अप',
    create_account: 'खाता बनाएं',
    whos_using: 'कौन Healio का उपयोग कर रहा है?',
    add_profile: 'प्रोफ़ाइल जोड़ें',
    setup_profile: 'प्रोफ़ाइल सेट अप करें',
    skip_for_now: 'अभी के लिए छोड़ें',
    date_of_birth: 'जन्म तिथि',
    gender: 'लिंग',
    optional: 'वैकल्पिक',
    emergency_contact: 'आपातकालीन संपर्क',
    already_have_account: 'पहले से ही एक खाता है?',
    dont_have_account: 'अकाउंट नहीं है?',
    male: 'पुरुष',
    female: 'महिला',
    other_gender: 'अन्य',
    tagline: 'आपका स्वास्थ्य साथी',
    // Patient registration
    signup_subtitle: 'अपनी स्वास्थ्य यात्रा प्रबंधित करने के लिए Healio से जुड़ें',
    full_name: 'पूरा नाम',
    full_name_ph: 'अपना पूरा नाम दर्ज करें',
    phone_ph: '10-अंकों का मोबाइल नंबर',
    dob_ph: 'जन्म तिथि चुनें',
    email_address: 'ईमेल पता',
    email_ph: 'ईमेल पता दर्ज करें (वैकल्पिक)',
    blood_group: 'रक्त समूह',
    blood_group_ph: 'रक्त समूह चुनें (वैकल्पिक)',
    select_blood_group: 'रक्त समूह चुनें',
    clear_selection: 'चयन साफ़ करें',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    AsyncStorage.getItem('app_language').then((saved) => {
      if (saved && translations[saved]) setLanguage(saved);
      setIsLoading(false);
    });
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    AsyncStorage.setItem('app_language', lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
