export const MOCK_DATA = {
  user: {
    id: '1',
    name: 'Arif Hossain',
    phone: '+91 9876543210',
    email: 'arif@example.com',
    bloodType: 'O+',
    height: '175 cm',
    weight: '72 kg',
    location: 'Dhaka, Bangladesh',
    avatar: null,
  },
  services: [
    { id: '1', name: 'Doctors', icon: 'person-add-outline', desc: 'Book consultations with specialists nearby' },
    { id: '2', name: 'Hospitals', icon: 'business-outline', desc: 'Find nearby hospitals & clinics' },
    { id: '3', name: 'Medicine', icon: 'medkit-outline', desc: 'Order medicines & healthcare products' },
    { id: '4', name: 'Labs', icon: 'flask-outline', desc: 'Diagnostic tests & health packages at home' },
    { id: '5', name: 'Home Care', icon: 'home-outline', desc: 'Nursing & assisted living' },
    { id: '6', name: 'Emergency', icon: 'alert-circle-outline', desc: 'Immediate medical help' },
    { id: '7', name: 'Ambulance', icon: 'car-outline', desc: '24/7 emergency transport' },
    { id: '8', name: 'Insurance', icon: 'shield-outline', desc: 'Health insurance & claims' },
  ],
  locations: [
    { id: '1', name: 'Dhaka, Bangladesh' },
    { id: '2', name: 'Chittagong, Bangladesh' },
    { id: '3', name: 'Sylhet, Bangladesh' },
    { id: '4', name: 'Rajshahi, Bangladesh' },
  ],
  appointments: [
    {
      id: 'a1',
      doctorId: 'd1',
      doctorName: 'Dr. Anita Sharma',
      specialty: 'Cardiologist',
      date: '12 Jun 2026',
      time: '10:00 AM',
      type: 'Video Consultation',
      status: 'Upcoming',
      location: 'Dhaka',
    },
    {
      id: 'a2',
      doctorId: 'd2',
      doctorName: 'Dr. Sameer Khan',
      specialty: 'Dermatologist',
      date: '15 May 2026',
      time: '02:30 PM',
      type: 'Clinic Visit',
      status: 'Past',
      location: 'Dhaka',
    },
    {
      id: 'a3',
      doctorId: 'd3',
      doctorName: 'Dr. Rajesh Gupta',
      specialty: 'Orthopedic',
      date: '10 May 2026',
      time: '11:00 AM',
      type: 'Video Consultation',
      status: 'Cancelled',
      location: 'Sylhet',
    },
  ],
  records: [
    {
      id: 'r1',
      type: 'Lab Report',
      title: 'Full Body Checkup',
      provider: 'Apollo Diagnostics',
      date: '24 May 2026',
      category: 'Lab Reports',
      icon: 'flask-outline',
      details: 'Hemoglobin: 14.5, Cholesterol: 180, Sugar: 95',
      status: 'Normal'
    },
    {
      id: 'r2',
      type: 'Prescription',
      title: 'Post-Viral Fatigue',
      provider: 'Dr. Anita Sharma',
      date: '22 May 2026',
      category: 'Prescriptions',
      icon: 'document-text-outline',
      details: 'Azithromycin 500mg, Vitamin C, Zinc supplements',
    },
    {
      id: 'r3',
      type: 'Bill',
      title: 'Monthly Medicines',
      provider: 'Healio Medicine',
      date: '20 May 2026',
      category: 'Payments',
      icon: 'wallet-outline',
      amount: '₹45.00',
      status: 'Paid'
    },
    {
      id: 'r4',
      type: 'Vaccination',
      title: 'COVID-19 Booster',
      provider: 'Central Hospital',
      date: '15 Apr 2026',
      category: 'Medical History',
      icon: 'shield-outline',
      details: 'Covaxin 3rd Dose - No side effects reported',
    },
    {
      id: 'r5',
      type: 'X-Ray',
      title: 'Chest X-Ray',
      provider: 'Ibn Sina Lab',
      date: '10 Apr 2026',
      category: 'Lab Reports',
      icon: 'scan-outline',
      details: 'Lungs clear, no abnormalities detected',
      status: 'Normal'
    },
    {
      id: 'r6',
      type: 'Prescription',
      title: 'Seasonal Allergy',
      provider: 'Dr. Sameer Khan',
      date: '05 Mar 2026',
      category: 'Prescriptions',
      icon: 'document-text-outline',
      details: 'Allegra 120mg, Nasal Spray',
    },
    {
      id: 'r7',
      type: 'Bill',
      title: 'Consultation Fee',
      provider: 'City Hospital',
      date: '02 Mar 2026',
      category: 'Payments',
      icon: 'wallet-outline',
      amount: '₹120.00',
      status: 'Paid'
    },
    {
      id: 'r8',
      type: 'Surgery',
      title: 'Appendectomy',
      provider: 'General Hospital',
      date: '12 Jan 2025',
      category: 'Medical History',
      icon: 'fitness-outline',
      details: 'Successful laparoscopic surgery',
    }
  ],
  doctors: [
    { id: 'd1', name: 'Dr. Anita Sharma', specialty: 'Cardiologist', reviews: 120, location: 'Dhaka', experience: '12 years', fee: '₹500', workingHours: { start: 9, end: 17, days: [1, 2, 3, 4, 5, 6] } },
    { id: 'd2', name: 'Dr. Sameer Khan', specialty: 'Dermatologist', reviews: 85, location: 'Dhaka', experience: '8 years', fee: '₹400', workingHours: { start: 10, end: 18, days: [1, 2, 3, 4, 5] } },
    { id: 'd3', name: 'Dr. Rajesh Gupta', specialty: 'Orthopedic', reviews: 210, location: 'Sylhet', experience: '15 years', fee: '₹600', workingHours: { start: 9, end: 14, days: [1, 2, 3, 4, 5, 6] } },
    { id: 'd4', name: 'Dr. Priya Das', specialty: 'Pediatrician', reviews: 340, location: 'Dhaka', experience: '10 years', fee: '₹450', workingHours: { start: 9, end: 20, days: [1, 2, 3, 4, 5, 6, 0] } },
  ],
  labs: [
    { id: 'l1', name: 'Apollo Diagnostics', location: 'Dhaka', tests: ['Blood Test', 'MRI', 'X-Ray'] },
    { id: 'l2', name: 'Popular Lab', location: 'Dhaka', tests: ['COVID Test', 'Glucose'] },
  ],
  pharmacies: [
    { id: 'p1', name: 'Lazz Pharma', location: 'Dhaka', availability: 'Open 24/7' },
    { id: 'p2', name: 'Healio Meds', location: 'Dhaka', availability: 'Closes at 10 PM' },
  ],
  hospitals: [
    { id: 'h1', name: 'Square Hospital', location: 'Dhaka', type: 'Tertiary Care', beds: '500+', specialties: 'Cardiology, ICU, Surgery', emergency: '24/7 Emergency', phone: '+880 2 1234 5678' },
    { id: 'h2', name: 'United Hospital', location: 'Dhaka', type: 'Multispecialty', beds: '400+', specialties: 'Orthopedics, Pediatrics, Internal Medicine', emergency: '24/7 Emergency', phone: '+880 2 8765 4321' },
  ],
  homeCare: [
    { id: 'hc1', name: 'LifeCare Nursing', location: 'Dhaka', specialty: 'Post-Surgery Care' },
    { id: 'hc2', name: 'Elderly Support', location: 'Dhaka', specialty: 'Geriatric Care' },
  ],
  emergency: [
    { id: 'e1', name: '24/7 Trauma Center', location: 'Dhaka', status: 'Available' },
    { id: 'e2', name: 'Urgent Care Clinic', location: 'Dhaka', status: 'Available' },
  ],
  ambulance: [
    { id: 'am1', name: 'City Ambulance', location: 'Dhaka', type: 'ICU Ambulance' },
    { id: 'am2', name: 'Quick Response', location: 'Dhaka', type: 'Basic Life Support' },
  ],
  insurance: [
    { id: 'i1', name: 'Healio Care Plus', coverage: 'Full Coverage', premium: '₹1200/mo' },
    { id: 'i2', name: 'Family Shield', coverage: 'Critical Illness', premium: '₹850/mo' },
  ]
};
